theme = "hugo-theme-relearn"

baseURL = 'http://example.org/'

relativeURLs = false
uglyURLs = true

languageCode = 'en'
defaultContentLanguage = "en"

title = 'Topper'

[markup.goldmark.renderer]
    unsafe = true
