editURL = "https://github.com/Topper-MC/Wiki/edit/main/content/"
description = "The Documentation for the Topper project"
author.name = "HSGamer"
showVisitedLinks = true
disableSearchHiddenPages = true
disableSeoHiddenPages = true
disableTagHiddenPages = true
collapsibleMenu = true
disableInlineCopyToClipBoard = true
disableNextPrev = false
disableSwagger = true
disableMathJax = true
disableLandingPageButton = true
themeVariant = [ "auto" ]
