project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "src/content/docs"
preserve_hierarchy: true

files:
  # Content pages (md/mdx)
  - source: /**/*.md
    translation: /%two_letters_code%/**/%original_file_name%
    ignore:
      - /??/**

  - source: /**/*.mdx
    translation: /%two_letters_code%/**/%original_file_name%
    ignore:
      - /??/**

  # i18n JSON (UI translations)
  - source: /i18n.json
    translation: /%two_letters_code%/i18n.json
