project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "src/content/docs"
preserve_hierarchy: true

files:
  # Content pages (md/mdx)
  - source: /**/*.md
    translation: /%locale%/**/%original_file_name%
    ignore:
      - /%locale%/**

  - source: /**/*.mdx
    translation: /%locale%/**/%original_file_name%
    ignore:
      - /%locale%/**

  # i18n JSON (UI translations)
  - source: /i18n.json
    translation: /%locale%/i18n.json
